<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DDTTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>48fc0ba9-c702-41df-9636-5d79d4affd5c</testSuiteGuid>
   <testCaseLink>
      <guid>fd32c0d0-2583-43a4-9fcb-323d5a87935c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/customerForDDT</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>07b7eaae-b61d-4bf8-8118-150c0d7da3c4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/customers</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>07b7eaae-b61d-4bf8-8118-150c0d7da3c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CusFirstName</value>
         <variableId>77af2d66-4750-44ed-90c7-4271881d5bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>07b7eaae-b61d-4bf8-8118-150c0d7da3c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CusLastName</value>
         <variableId>02515ae7-ee0d-46d8-8ecd-99b606906bef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>07b7eaae-b61d-4bf8-8118-150c0d7da3c4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CusPostCode</value>
         <variableId>54129b8d-f915-420f-813f-09b17952fd07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05483bb4-5043-4847-8a49-a4691e7edb4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00bad254-ff1c-42ac-81fc-d419fb3b6d1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f7988f6-48aa-4db2-8bd2-8646fc218c0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02b9c216-9d8e-47c9-a3f9-a75614db02f9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
