<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Jun 9, 2023 24529 PM</name>
   <tag></tag>
   <elementGuidId>24683082-a125-4191-a52d-4bfd0ce1c2e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor0']/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a8fae369-73c0-4b07-a886-92495f1f773e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>715f5b0c-28ec-4020-ae2f-5e84d9c7c3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jun 9, 2023 2:45:29 PM</value>
      <webElementGuid>39fc5d5e-a3cf-46c4-9e04-f18bec5803cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor0&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>976d7459-09bd-447f-a9ec-c8af9c9042d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor0']/td</value>
      <webElementGuid>040ad766-6c65-4f97-9b64-39aee7be2074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Type'])[1]/following::td[1]</value>
      <webElementGuid>ec3864cf-60ca-4a1c-ad04-4d9cb5ecb87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::td[2]</value>
      <webElementGuid>847b1c61-590f-4eb2-bc86-eb4083e300b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit'])[1]/preceding::td[2]</value>
      <webElementGuid>b97859d8-2e45-4eba-8a65-78ee14137917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun 9, 2023 2:46:23 PM'])[1]/preceding::td[3]</value>
      <webElementGuid>94fb5bed-58b8-487d-b110-2eff697b2e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jun 9, 2023 2:45:29 PM']/parent::*</value>
      <webElementGuid>ab196c98-2787-4787-a5e8-79a91f330989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>e7dbc1ac-9317-462f-a542-74fd2d5f7a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Jun 9, 2023 2:45:29 PM' or . = 'Jun 9, 2023 2:45:29 PM')]</value>
      <webElementGuid>dcafbc94-818a-4990-8ece-2ccf89e3cffa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
